# Generated by Django 5.2.2 on 2025-06-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='dishes/')),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('drinks', 'Drinks')], max_length=10)),
                ('is_veg', models.BooleanField(default=False)),
            ],
        ),
    ]
